import type { MenuItem, StoreId } from "@/types";

/** 스타벅스 메뉴 (27개) */
export const STARBUCKS_MENUS: MenuItem[] = [
  { id: "sb01", name: "아이스 아메리카노",          category: "에스프레소" },
  { id: "sb02", name: "카페 아메리카노",             category: "에스프레소" },
  { id: "sb03", name: "카페 라떼",                  category: "에스프레소" },
  { id: "sb04", name: "아이스 카페 라떼",            category: "에스프레소" },
  { id: "sb05", name: "바닐라 라떼",                category: "에스프레소" },
  { id: "sb06", name: "아이스 바닐라 라떼",          category: "에스프레소" },
  { id: "sb07", name: "카라멜 마키아또",             category: "에스프레소" },
  { id: "sb08", name: "아이스 카라멜 마키아또",      category: "에스프레소" },
  { id: "sb09", name: "카푸치노",                    category: "에스프레소" },
  { id: "sb10", name: "카페 모카",                  category: "에스프레소" },
  { id: "sb11", name: "아이스 카페 모카",            category: "에스프레소" },
  { id: "sb12", name: "돌체 라떼",                  category: "에스프레소" },
  { id: "sb13", name: "플랫 화이트",                category: "에스프레소" },
  { id: "sb14", name: "에스프레소",                  category: "에스프레소" },
  { id: "sb20", name: "콜드 브루",                  category: "콜드브루" },
  { id: "sb21", name: "나이트로 콜드 브루",          category: "콜드브루" },
  { id: "sb22", name: "돌체 콜드 브루",             category: "콜드브루" },
  { id: "sb23", name: "콜드 브루 라떼",             category: "콜드브루" },
  { id: "sb30", name: "자바 칩 프라푸치노",          category: "프라푸치노" },
  { id: "sb31", name: "카라멜 프라푸치노",           category: "프라푸치노" },
  { id: "sb32", name: "모카 프라푸치노",             category: "프라푸치노" },
  { id: "sb33", name: "더블 에스프레소 칩 프라푸치노", category: "프라푸치노" },
  { id: "sb34", name: "그린 티 크림 프라푸치노",     category: "프라푸치노" },
  { id: "sb35", name: "바닐라 크림 프라푸치노",      category: "프라푸치노" },
  { id: "sb40", name: "그린 티 라떼",               category: "티/리프레셔" },
  { id: "sb41", name: "아이스 그린 티 라떼",         category: "티/리프레셔" },
  { id: "sb42", name: "자몽 허니 블랙 티",           category: "티/리프레셔" },
  { id: "sb43", name: "복숭아 아이스 티",            category: "티/리프레셔" },
  { id: "sb44", name: "딸기 아사이 리프레셔",        category: "티/리프레셔" },
  { id: "sb45", name: "망고 드래곤 프루트 리프레셔", category: "티/리프레셔" },
  { id: "sb46", name: "핑크 드링크",                category: "티/리프레셔" },
];

/** 메가커피 메뉴 (38개) */
export const MEGA_MENUS: MenuItem[] = [
  { id: "mg01", name: "아메리카노",           category: "커피" },
  { id: "mg02", name: "메가리카노",           category: "커피" },
  { id: "mg03", name: "꿀아메리카노",         category: "커피" },
  { id: "mg04", name: "헤이즐넛아메리카노",   category: "커피" },
  { id: "mg05", name: "바닐라아메리카노",     category: "커피" },
  { id: "mg06", name: "카페라떼",             category: "커피" },
  { id: "mg07", name: "바닐라라떼",           category: "커피" },
  { id: "mg08", name: "헤이즐넛라떼",         category: "커피" },
  { id: "mg09", name: "카푸치노",             category: "커피" },
  { id: "mg10", name: "연유라떼",             category: "커피" },
  { id: "mg11", name: "흑당라떼",             category: "커피" },
  { id: "mg12", name: "오레오초코라떼",       category: "커피" },
  { id: "mg13", name: "초코라떼",             category: "커피" },
  { id: "mg14", name: "콜드브루",             category: "커피" },
  { id: "mg15", name: "콜드브루라떼",         category: "커피" },
  { id: "mg16", name: "할메가커피",           category: "커피" },
  { id: "mg17", name: "왕할메가커피",         category: "커피" },
  { id: "mg20", name: "그린티라떼",           category: "티" },
  { id: "mg21", name: "얼그레이라떼",         category: "티" },
  { id: "mg22", name: "로얄밀크티",           category: "티" },
  { id: "mg23", name: "딸기밀크티",           category: "티" },
  { id: "mg24", name: "왕메가아이스티",       category: "티" },
  { id: "mg25", name: "복숭아아이스티",       category: "티" },
  { id: "mg30", name: "메가에이드",           category: "에이드&주스" },
  { id: "mg31", name: "자몽에이드",           category: "에이드&주스" },
  { id: "mg32", name: "레몬에이드",           category: "에이드&주스" },
  { id: "mg33", name: "청포도에이드",         category: "에이드&주스" },
  { id: "mg34", name: "체리콕",               category: "에이드&주스" },
  { id: "mg35", name: "딸기바나나주스",       category: "에이드&주스" },
  { id: "mg36", name: "망고주스",             category: "에이드&주스" },
  { id: "mg40", name: "딸기라떼",             category: "스무디&프라페" },
  { id: "mg41", name: "고구마라떼",           category: "스무디&프라페" },
  { id: "mg42", name: "퐁크러쉬(플레인)",     category: "스무디&프라페" },
  { id: "mg43", name: "퐁크러쉬(딸기)",       category: "스무디&프라페" },
  { id: "mg44", name: "퐁크러쉬(초코)",       category: "스무디&프라페" },
  { id: "mg45", name: "쿠키프라페",           category: "스무디&프라페" },
  { id: "mg46", name: "민트초코프라페",       category: "스무디&프라페" },
  { id: "mg47", name: "코코넛커피스무디",     category: "스무디&프라페" },
  { id: "mg50", name: "디카페인 아메리카노",  category: "디카페인" },
  { id: "mg51", name: "디카페인 카페라떼",    category: "디카페인" },
  { id: "mg52", name: "디카페인 바닐라라떼",  category: "디카페인" },
];

/** 커피빈 메뉴 (46개) */
export const COFFEEBEAN_MENUS: MenuItem[] = [
  { id: "cb01", name: "아이스 아메리카노",          category: "에스프레소" },
  { id: "cb02", name: "아메리카노",                  category: "에스프레소" },
  { id: "cb03", name: "아이스 헤이즐넛 아메리카노",  category: "에스프레소" },
  { id: "cb04", name: "헤이즐넛 아메리카노",         category: "에스프레소" },
  { id: "cb05", name: "카페 라떼",                  category: "에스프레소" },
  { id: "cb06", name: "아이스 카페 라떼",            category: "에스프레소" },
  { id: "cb07", name: "커피빈 라떼",                category: "에스프레소" },
  { id: "cb08", name: "아이스 커피빈 라떼",          category: "에스프레소" },
  { id: "cb09", name: "바닐라 라떼",                category: "에스프레소" },
  { id: "cb10", name: "아이스 바닐라 라떼",          category: "에스프레소" },
  { id: "cb11", name: "바닐라빈 오트 라떼",          category: "에스프레소" },
  { id: "cb12", name: "아이스 바닐라빈 오트 라떼",   category: "에스프레소" },
  { id: "cb13", name: "캐러멜 마끼아또",             category: "에스프레소" },
  { id: "cb14", name: "아이스 캐러멜 마끼아또",      category: "에스프레소" },
  { id: "cb15", name: "카푸치노",                    category: "에스프레소" },
  { id: "cb16", name: "플랫 화이트",                category: "에스프레소" },
  { id: "cb17", name: "달고나 크림 라떼",            category: "에스프레소" },
  { id: "cb18", name: "카페 수아",                  category: "에스프레소" },
  { id: "cb20", name: "오리지널 아이스 블렌디드",    category: "아이스 블렌디드" },
  { id: "cb21", name: "모카 아이스 블렌디드",        category: "아이스 블렌디드" },
  { id: "cb22", name: "헤이즐넛 아이스 블렌디드",    category: "아이스 블렌디드" },
  { id: "cb23", name: "바닐라 아이스 블렌디드",      category: "아이스 블렌디드" },
  { id: "cb24", name: "그린티 아이스 블렌디드",      category: "아이스 블렌디드" },
  { id: "cb25", name: "딸기 아이스 블렌디드",        category: "아이스 블렌디드" },
  { id: "cb26", name: "망고 아이스 블렌디드",        category: "아이스 블렌디드" },
  { id: "cb30", name: "얼그레이 티",                category: "티" },
  { id: "cb31", name: "아이스 얼그레이 티",          category: "티" },
  { id: "cb32", name: "잉글리쉬 브렉퍼스트 티",      category: "티" },
  { id: "cb33", name: "캐모마일 티",                category: "티" },
  { id: "cb34", name: "페퍼민트 티",                category: "티" },
  { id: "cb35", name: "레몬 민트 티",               category: "티" },
  { id: "cb40", name: "제주 말차 라떼",             category: "티 라떼" },
  { id: "cb41", name: "아이스 제주 말차 라떼",       category: "티 라떼" },
  { id: "cb42", name: "헤이즐넛 말차 라떼",          category: "티 라떼" },
  { id: "cb43", name: "아이스 헤이즐넛 말차 라떼",   category: "티 라떼" },
  { id: "cb44", name: "로얄 밀크티 라떼",           category: "티 라떼" },
  { id: "cb45", name: "아이스 로얄 밀크티 라떼",     category: "티 라떼" },
];

/** 스토어 ID에 맞는 메뉴 목록 반환 */
export function getMenus(storeId: StoreId | string): MenuItem[] {
  switch (storeId) {
    case "starbucks":  return STARBUCKS_MENUS;
    case "mega":       return MEGA_MENUS;
    case "coffeebean": return COFFEEBEAN_MENUS;
    default:           return [];
  }
}
